{{- if .Values.ingress.enabled -}}
{{- $fullName := include "loomvec.fullname" . -}}
{{- $svcPorts := dict "api" .Values.api.port "web" .Values.web.port "admin" .Values.admin.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "loomvec.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-{{ .service }}
                port:
                  number: {{ get $svcPorts .service }}
          {{- end }}
    {{- end }}
{{- end }}
