apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loomvec.fullname" . }}-web
  labels:
    {{- include "loomvec.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  {{- with .Values.web.strategy }}
  strategy:
    {{- include "loomvec.updateStrategy" . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "loomvec.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "loomvec.componentLabels" (dict "component" "web" "context" .) | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "loomvec.serviceAccountName" . }}
      containers:
        - name: web
          image: {{ include "loomvec.image" (dict "root" $ "image" .Values.web.image) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loomvec.fullname" . }}-web
  labels:
    {{- include "loomvec.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
  selector:
    {{- include "loomvec.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
